language: python
python: '3.6'
branches:
  only:
  - master
  - develop

install:
  - pip install -r requirements-ci.txt

script:
  - set -e
  - flake8 dohq_common
  - coverage run -m py.test tests
  - coverage xml

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "gQlhyPumUUAUYFHZVJglktXp845Lw1A9SKjW3YCFIZlxilcdYXpLdN2N/QRj10fUPbpYTTpcn6sId13PmPXeT9pXjlFJdWY+mMBZmnrA8dQLTOmrzqBj2Ee0L9Rh+uyHItrUiN2ir+WLYgFe20wYTSkUhNwBzgiTfYwiLlHOBJMxC3Yn5sNcekBATEJMOf7Qo68YSW5d0za584zxQyMQPFa630jv0EJ1s7t4tRM5UPfBKbTLs2VgDHdHOgi7DvSlKXZYmczzooDzBYdUni9lCkcymMgCHudRtQV/fYGnUHgzvqAPmrbUSyhviyAWS8gdy6nihq3SLpxRnvLfrN3MR+118SVn8q1vFwAh9qzyFUXI3dk4YKPdkx97ZYrIQgCiUjCXlFbPmZC57f6PummW/xAzrkSUiIFuVoaYe/iOGlTks9kDKSGEVMzyHE8bpb4GPJVZMRB7xbOqQqail6MXrYu3QCHXuXSAOizgbvTcmomWJE3hY+UhzcRuQeZL8DF/ajVp/UecobPKqe+mC1g2PxHhJOkB2GfcSWRbSv00IGzXBv8E4pYuWNaL17NVbb8wLG8RNWE0I6ssJhcwFdwAkzRS08dBO1WLZ1wJjjVQjbPFEhNKaxnNtVS5DStENn2ejOPEu4704KEbwj4h9KgTLFJHji2yW1r7j4qpzkRW2qM="
  distributions: sdist bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true

after_script:
  - echo "Deploy to PyPI finished."