language: python
python: '3.7'
branches:
  only:
  - master
  - develop

install:
  - pip install pytest coverage codacy-coverage

script:
  - coverage run -m py.test tests
  - coverage xml

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "pypi-AgEIcHlwaS5vcmcCJDI1N2U1M2MzLTY3MjctNGYxZS04MWViLTVlOTZlMWU4YWUyYQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgd4XTlM1I9EH34Q2G7zHIHAn4TNGVl1a-3ekgZmshXWg"
  distributions: sdist bdist_wheel
  on:
    all_branches: true
  skip_cleanup: true

after_script:
  - echo "Deploy to PyPI finished."